server:
  port: 9090
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  application:
    name: dvk-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:osr}?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true